parameters:
#    orestad_checklist.example.class: Orestad\ChecklistBundle\Example

services:
#    orestad_checklist.example:
#        class: %orestad_checklist.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
