orestad_checklist:
    resource: "@OrestadChecklistBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: OrestadChecklistBundle:Secured:login }
login_check:
    pattern:   /login_check

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
